import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";
import { AuthProvider } from "@/app/context/AuthProvider"
import { Suspense } from "react";
import { NavigationEvents } from "./components/navigation-event/navigation-event";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navigation />
          {children}

        </AuthProvider>
      </body>
    </html >
  );
}
